---
- name: Create File Systems
  hosts: '{{ target }}'
  become: yes
  gather_facts: true
  vars:
    pvs: []
  tasks:
    - name: Create a new primary partition for LVM
      community.general.parted:
        device: '{{ new_disk }}'
        number: 1
        flags: [ lvm ]
        state: present
        part_start: "0%"
        part_end: "100%"
        name: "smol data"
        label: "gpt"
    - name: Create list of PVs
      set_fact:
        pvs: '{{ pvs + [item] }}'
      loop: "{{ansible_facts['lvm']['pvs'] | dict2items | selectattr('value.vg', 'eq', 'rhel') | map(attribute='key') | list }}"
    - name: Add new pv to list
      set_fact:
        pvs: '{{ pvs + [new_disk'1'] }}'
    - name:
      debug:
        msg: "{{ pvs }}"
    - name: Grow Volume Group
      community.general.lvg:
        vg: "rhel"
        pvs: '{{ pvs }} '
    - name: Extend the logical volume by given space
      community.general.lvol:
        vg: "rhel"
        lv: var
        size: +5G
        resizefs: true
    - name: Create the remaining logical volume by given space
      community.general.lvol:
        vg: "rhel"
        lv: data
        size: 100%FREE
    - name: Create a xfs filesystem on /dev/mapper/rhel-data
      community.general.filesystem:
        fstype: xfs
        dev: /dev/mapper/rhel-data
    - name: Mount up device by label
      ansible.posix.mount:
        path: /data
        src: /dev/mapper/rhel-data
        fstype: xfs
        state: mounted