---
- name: Server Report
  hosts: all
  become: yes
  gather_facts: true
  tasks:
    - name: Report Server Facts
      ansible.builtin.debug:
        msg:
          - "Hostname: {{ ansible_fqdn }}"
          - "MEMORY: {{ ansible_memtotal_mb }}"
          - "BIOS: {{ ansible_bios_version }}"
          - "SDA_DISK_SIZE: {{ ansible_disks[sda].size }}"
          - "SDB_DISK_SIZE: {{ ansible_disks[sdb].size }}"